source 'http://rubygems.org'
gem 'sinatra'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'haml', '>= 2.2.0'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'shotgun'
gem 'time-ago-in-words'
gem 'dm-postgres-adapter'
gem 'datamapper', '~> 1.2.0'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'sinatra-flash'
